geometric sequences
IncendiumAcademy/site pull request #11
Opened 2020-12-14 04:00 UTC by thejammerr

2020-12-17 21:08 UTC, 0ffz requested changes

2020-12-17 21:08 UTC, 0ffz commented on content/math/algebra/geometry/circle-geometry/inscribed-central-angles.md
> +<div class="embed-container">
Should use `{% include youtubePlayer.html id="JIXOlER7qXU" %}` instead. Same goes for any of the other videos.

2020-12-18 01:28 UTC, thejammerr commented on content/math/algebra/geometry/circle-geometry/inscribed-central-angles.md
> +<div class="embed-container">
where exactly?

2020-12-18 01:29 UTC, 0ffz commented on content/math/algebra/geometry/circle-geometry/inscribed-central-angles.md
> +<div class="embed-container">
Just replace the entire div container for all the pages where u used it

2020-12-18 14:05 UTC, 0ffz requested changes
Just some more stuff I noticed, other than that, it looks good

2020-12-18 14:05 UTC, 0ffz commented on content/math/algebra/geometry/circle-geometry/inscribed-central-angles.md
> +title: Inscribed and Central Angles
```suggestion
title: Inscribed and Central Angles
author: Richard Hanxu
```

2020-12-18 14:05 UTC, 0ffz commented on content/math/algebra/geometry/circle-geometry/thales-theorem.md
> +<br>
No need for a line break, two enters does the job.

2020-12-18 14:05 UTC, 0ffz commented on content/math/algebra/geometry/circle-geometry/inscribed-central-angles.md
> +# Inscribed and Central Angles
No need to repeat the lesson name, the `title` tag will put it on the page anyways.
```suggestion
```

2020-12-18 18:19 UTC, merged